### ISSUE TITLE
Script editor does not launch

### ISSUE THREAD

**Issue by Question2** [FakelsHub/sfall_script_editor#13]
I just downloaded and installed v4.1.7.RC and tried to start the .exe. It askes me if i want to associate the extensions with sfall. I click yes. Nothing happens afterwards...

sse.log just says :

Run main editor...
   Load configuration setting.

Am i missing something here?

**Comment by Question2** [comment]
Nevermind, did not realise i was supposed to open .ssl files directly, someone on discord was telling me to run the exe.

**Comment by Lexx2k** [comment]
If you run the exe, you get a button with "open" in the top left corner ... that's where you open .ssl files from ...

**Comment by Question2** [comment]
The program didnt launch for me at all when i tried that. Not sure why. It seems to do that now though.

**Comment by narczi** [comment]
It works if you press "No" when it asks you to associate files. There must be some problem with associating files, probably a Windows 10 thing, because even if you press "Yes" it still doesn't make .ssl files open with the editor.

**Comment by FakelsHub** [comment]
Fuck this buggy Windows 10. Contact Microsoft and let them finish their incompatible OS!
