### ISSUE TITLE
Disable automatic file association

### ISSUE THREAD

**Issue by phobos2077** [FakelsHub/sfall_script_editor#8]
Думаю стоит убрать автоматическую ассоциацию файлов .int, .ssl с редактором при первом запуске. Слишком навязчиво для пользователя :)

**Comment by FakelsHub** [comment]
Да я думал об этот. Поэтому в коде если ассоциация ssl уже существует в системе, то не делать ассоциацию. Видимо что-то с реестром не так работает. Надо еще потестить.
Переделаю для надежности по простому, с запросом у пользователя.

**Comment by phobos2077** [comment]
Да спросить у пользователя будет правильно, только вредоносное ПО без разрешения такие вещи делает)))
